<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="ULTP_722"><DocLocation><![CDATA[E:\Sprint\Scripts\Costco\Single Drug Batch Processing\Sprint 1\SDBP_Sprint1]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[SDBP_Sprint1]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Unit Cost]]></Obj>
<Details ><![CDATA[Unit Cost pricing setting has been set to User required value]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:36]]></Time>
<TimeTick>1501057776</TimeTick>
<NodeArgs eType="User" icon="3" nRep="6" >
<Disp><![CDATA[Unit Cost]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Enterprise Pharmacy System]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:54]]></Time>
<TimeTick>1501057794</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Filecabinet]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:54]]></Time>
<TimeTick>1501057794</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Prescriber]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:54]]></Time>
<TimeTick>1501057794</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Third Party]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:54]]></Time>
<TimeTick>1501057794</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Third Party.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:54]]></Time>
<TimeTick>1501057794</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" >
<Disp><![CDATA[Third Party.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="13" >
<Disp><![CDATA[Third Party]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="12" >
<Disp><![CDATA[Prescriber]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="11" >
<Disp><![CDATA[Filecabinet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Prescriber Search]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:54]]></Time>
<TimeTick>1501057794</TimeTick>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Last Name.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", 1, "1", 20000]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:55]]></Time>
<TimeTick>1501057795</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="17" >
<Disp><![CDATA[Last Name.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Last Name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Prescriber"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:55]]></Time>
<TimeTick>1501057795</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" >
<Disp><![CDATA[Last Name.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[First Name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Adjudication"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:55]]></Time>
<TimeTick>1501057795</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="21" >
<Disp><![CDATA[First Name.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[find.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:55]]></Time>
<TimeTick>1501057795</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="22" >
<Disp><![CDATA[find.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[find.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:55]]></Time>
<TimeTick>1501057795</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="24" >
<Disp><![CDATA[find.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Select.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:55]]></Time>
<TimeTick>1501057795</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="26" >
<Disp><![CDATA[Select.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="16" >
<Disp><![CDATA[Prescriber Search]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Plan Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["GING"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:55]]></Time>
<TimeTick>1501057795</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="28" >
<Disp><![CDATA[Plan Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[find.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:55]]></Time>
<TimeTick>1501057795</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="29" >
<Disp><![CDATA[find.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[find.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:55]]></Time>
<TimeTick>1501057795</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="31" >
<Disp><![CDATA[find.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[Insurance Plan Search]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Insurance Plan Search.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="33" >
<Disp><![CDATA[Insurance Plan Search.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Select.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="35" >
<Disp><![CDATA[Select.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="32" >
<Disp><![CDATA[Insurance Plan Search]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Prescriber ID.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["PET"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="37" >
<Disp><![CDATA[Prescriber ID.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[NCPDP ID Qualifier.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Plan Specific"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="39" >
<Disp><![CDATA[NCPDP ID Qualifier.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Save.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="40" >
<Disp><![CDATA[Save.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="42" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Duplicate Validation]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[Duplicate Validation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="44" >
<Disp><![CDATA[Duplicate Validation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="46" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="43" >
<Disp><![CDATA[Duplicate Validation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[Back to Home.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="47" >
<Disp><![CDATA[Back to Home.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Back to Home.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 13:59:56]]></Time>
<TimeTick>1501057796</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="49" >
<Disp><![CDATA[Back to Home.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Filecabinet]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Prescriber]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[Third Party]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Third Party.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="54" >
<Disp><![CDATA[Third Party.Select]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="53" >
<Disp><![CDATA[Third Party]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="52" >
<Disp><![CDATA[Prescriber]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="51" >
<Disp><![CDATA[Filecabinet]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Prescriber Search]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Last Name.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", 1, "1", 20000]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="57" >
<Disp><![CDATA[Last Name.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[Last Name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Prescriber"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="59" >
<Disp><![CDATA[Last Name.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[First Name.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["Adjudication"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="61" >
<Disp><![CDATA[First Name.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[find.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="62" >
<Disp><![CDATA[find.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[find.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="64" >
<Disp><![CDATA[find.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T43">
<Obj plainTxt="False" ><![CDATA[Select.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="66" >
<Disp><![CDATA[Select.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="56" >
<Disp><![CDATA[Prescriber Search]]></Disp>
</NodeArgs>
</Step>
<Step rID="T44">
<Obj plainTxt="False" ><![CDATA[Plan Search.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["AET"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="68" >
<Disp><![CDATA[Plan Search.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T45">
<Obj plainTxt="False" ><![CDATA[find.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:02]]></Time>
<TimeTick>1501057802</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" >
<Disp><![CDATA[find.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T46">
<Obj plainTxt="False" ><![CDATA[find.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="71" >
<Disp><![CDATA[find.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T47">
<Obj plainTxt="False" ><![CDATA[Insurance Plan Search]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<Step rID="T48">
<Obj plainTxt="False" ><![CDATA[Insurance Plan Search.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="73" >
<Disp><![CDATA[Insurance Plan Search.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T49">
<Obj plainTxt="False" ><![CDATA[Select.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="75" >
<Disp><![CDATA[Select.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="72" >
<Disp><![CDATA[Insurance Plan Search]]></Disp>
</NodeArgs>
</Step>
<Step rID="T50">
<Obj plainTxt="False" ><![CDATA[Prescriber ID.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["PET"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="77" >
<Disp><![CDATA[Prescriber ID.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T51">
<Obj plainTxt="False" ><![CDATA[NCPDP ID Qualifier.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["Plan Specific"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="11" nRep="79" >
<Disp><![CDATA[NCPDP ID Qualifier.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T52">
<Obj plainTxt="False" ><![CDATA[Save.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="80" >
<Disp><![CDATA[Save.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T53">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="82" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T54">
<Obj plainTxt="False" ><![CDATA[Duplicate Validation]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<Step rID="T55">
<Obj plainTxt="False" ><![CDATA[Duplicate Validation.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="84" >
<Disp><![CDATA[Duplicate Validation.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T56">
<Obj plainTxt="False" ><![CDATA[OK.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="86" >
<Disp><![CDATA[OK.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="83" >
<Disp><![CDATA[Duplicate Validation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T57">
<Obj plainTxt="False" ><![CDATA[Back to Home.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="87" >
<Disp><![CDATA[Back to Home.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T58">
<Obj plainTxt="False" ><![CDATA[Back to Home.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:03]]></Time>
<TimeTick>1501057803</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="89" >
<Disp><![CDATA[Back to Home.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T59">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[26-07-2017 - 14:00:06]]></Time>
<TimeTick>1501057806</TimeTick>
<NodeArgs eType="General" icon="12" nRep="90" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="10" >
<Disp><![CDATA[Enterprise Pharmacy System]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="26-07-2017 - 13:59:36" eTime="26-07-2017 - 14:00:06" passed="0" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="4" nRep="7" >
<Disp><![CDATA[SDBP_Sprint1 Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="26-07-2017 - 13:59:35" eTime="26-07-2017 - 14:00:06" passed="0" failed="0" warnings="0" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" >
<Disp><![CDATA[Test SDBP_Sprint1 Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>