<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="ULTP_722"><DocLocation><![CDATA[E:\Sprint\Scripts\Costco\Login Security and Supplemental Roles\Corporate Authentication\AD_SETUP\AD_Setup_Main_RF]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[AD_Setup_Main_RF]]></DName>
<Res><![CDATA[Res7]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Certificate Error: Navigation]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:13]]></Time>
<TimeTick>1499941093</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA["Certificate Error: Navigation"- Smart Identification]]></Obj>
<Details plainTxt="False" ><![CDATA[<P><span class="text">The smart identification mechanism was invoked.</span></P><P><SPAN class=text>Reason: object not unique (6 objects found)</SPAN></P>           <SPAN class=text><b>Original description:</b></SPAN><br>micclass=Browser<br><P><FONT face=Verdana size=2><SPAN class=text><B>Smart Identification Alternative Description: </B></SPAN></FONT></P><FONT face=Verdana size=2><u>Base filter properties (6 objects found)&nbsp;</FONT></u><br>
micclass=Browser<br><br><FONT face=Verdana size=2><u>Optional filter properties</FONT></u><br>
name=Certificate Error: Navigation Blocked<SPAN class=Failed> (Skipped)</SPAN><br>title=Enterprise Control Center Login<SPAN class=Failed> (Skipped)</SPAN><br>openurl=res://ieframe.dll/invalidcert.htm?SSLError=58720384#https://192.168.109.121:58442/ecc/login.jsp<SPAN class=passed> (Used</SPAN>, 1 matches)</SPAN><br>opentitle=Certificate Error: Navigation Blocked<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasstatusbar=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hasmenubar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>hastoolbar=-1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>openedbytestingtool=0<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>number of tabs=1<SPAN class=warning> (Ignored)<FONT color=#000000></FONT></SPAN><br>]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:13]]></Time>
<TimeTick>1499941093</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="9" >
<Disp><![CDATA["Certificate Error: Navigation"- Smart Identification]]></Disp>
</NodeArgs>
</Step>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Enterprise Control Center_3]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:13]]></Time>
<TimeTick>1499941093</TimeTick>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[header-form:j_id91:anchor.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:13]]></Time>
<TimeTick>1499941093</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="12" >
<Disp><![CDATA[header-form:j_id91:anchor.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="11" >
<Disp><![CDATA[Enterprise Control Center_3]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[ECC Configuration - Communication]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:14]]></Time>
<TimeTick>1499941094</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Edit.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 20000]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:14]]></Time>
<TimeTick>1499941094</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" >
<Disp><![CDATA[Edit.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Edit.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:14]]></Time>
<TimeTick>1499941094</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="18" >
<Disp><![CDATA[Edit.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Edit.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:14]]></Time>
<TimeTick>1499941094</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="21" >
<Disp><![CDATA[Edit.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:adHost.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["10.204.13.56"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:16]]></Time>
<TimeTick>1499941096</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="24" >
<Disp><![CDATA[eccCommSettingsForm:adHost.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:adPort.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["636"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:16]]></Time>
<TimeTick>1499941096</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="27" >
<Disp><![CDATA[eccCommSettingsForm:adPort.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:j_id162.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["LDAPS"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:16]]></Time>
<TimeTick>1499941096</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="30" >
<Disp><![CDATA[eccCommSettingsForm:j_id162.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:j_id169.Select]]></Obj>
<Details plainTxt="False" ><![CDATA["TLSv1"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:16]]></Time>
<TimeTick>1499941096</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="33" >
<Disp><![CDATA[eccCommSettingsForm:j_id169.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:adSystemUsernam.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["SVC-EPS-RO"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:16]]></Time>
<TimeTick>1499941096</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="36" >
<Disp><![CDATA[eccCommSettingsForm:adSystemUsernam.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:adSystemPasswor.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["f,[}\d+2Cj"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:16]]></Time>
<TimeTick>1499941096</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="39" >
<Disp><![CDATA[eccCommSettingsForm:adSystemPasswor.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:maxResponseTime.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["1000"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:17]]></Time>
<TimeTick>1499941097</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="42" >
<Disp><![CDATA[eccCommSettingsForm:maxResponseTime.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:adPasswordReset.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["https://www.pdxinc.com/credentials.asp"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:17]]></Time>
<TimeTick>1499941097</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="45" >
<Disp><![CDATA[eccCommSettingsForm:adPasswordReset.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:adTrustedKeySto.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["/home/eccadmin/ADTrustStore.jks"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:17]]></Time>
<TimeTick>1499941097</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="48" >
<Disp><![CDATA[eccCommSettingsForm:adTrustedKeySto.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:adTrustedKeySto_2.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ADTRUSTPASS"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:17]]></Time>
<TimeTick>1499941097</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="51" >
<Disp><![CDATA[eccCommSettingsForm:adTrustedKeySto_2.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Test Communication Setup.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:19]]></Time>
<TimeTick>1499941099</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="53" >
<Disp><![CDATA[Test Communication Setup.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T23">
<Obj plainTxt="False" ><![CDATA[Test Communication Setup.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:19]]></Time>
<TimeTick>1499941099</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="56" >
<Disp><![CDATA[Test Communication Setup.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T24">
<Obj plainTxt="False" ><![CDATA[Configuration Test Passed.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:21]]></Time>
<TimeTick>1499941101</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="72" >
<Disp><![CDATA[Configuration Test Passed.Exist]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="15" >
<Disp><![CDATA[ECC Configuration - Communication]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" >
<Disp><![CDATA[Certificate Error: Navigation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T25">
<Obj ><![CDATA[Configuration Test for Communication Settings]]></Obj>
<Details ><![CDATA[Passed]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:21]]></Time>
<TimeTick>1499941101</TimeTick>
<NodeArgs eType="User" icon="11" nRep="73" status="Passed" >
<Disp><![CDATA[Configuration Test for Communication Settings]]></Disp>
</NodeArgs>
</Step>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Certificate Error: Navigation]]></Obj>
<Details plainTxt="False" ><![CDATA[Browser]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:21]]></Time>
<TimeTick>1499941101</TimeTick>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[ECC Configuration - Communication]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:21]]></Time>
<TimeTick>1499941101</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[close.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:21]]></Time>
<TimeTick>1499941101</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="77" >
<Disp><![CDATA[close.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[close.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:21]]></Time>
<TimeTick>1499941101</TimeTick>
<NodeArgs eType="Replay" icon="12" nRep="80" >
<Disp><![CDATA[close.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="76" >
<Disp><![CDATA[ECC Configuration - Communication]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[ECC Configuration - Communication_2]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:21]]></Time>
<TimeTick>1499941101</TimeTick>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:j_id207.WaitProperty]]></Obj>
<Details plainTxt="False" ><![CDATA["visible", True, True, 20000]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:21]]></Time>
<TimeTick>1499941101</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="84" >
<Disp><![CDATA[eccCommSettingsForm:j_id207.WaitProperty]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[eccCommSettingsForm:j_id207.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ON"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:21]]></Time>
<TimeTick>1499941101</TimeTick>
<NodeArgs eType="Replay" icon="13" nRep="87" >
<Disp><![CDATA[eccCommSettingsForm:j_id207.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T33">
<Obj plainTxt="False" ><![CDATA[Save.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:23]]></Time>
<TimeTick>1499941103</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="89" >
<Disp><![CDATA[Save.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T34">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:23]]></Time>
<TimeTick>1499941103</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="92" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="83" >
<Disp><![CDATA[ECC Configuration - Communication_2]]></Disp>
</NodeArgs>
</Step>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[ECC Configuration - Communication]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:24]]></Time>
<TimeTick>1499941104</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[WebTable.Exist]]></Obj>
<Details plainTxt="False" ><![CDATA["Object exists"]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:24]]></Time>
<TimeTick>1499941104</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="95" >
<Disp><![CDATA[WebTable.Exist]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[WebTable.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:24]]></Time>
<TimeTick>1499941104</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="98" >
<Disp><![CDATA[WebTable.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="94" >
<Disp><![CDATA[ECC Configuration - Communication]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="75" >
<Disp><![CDATA[Certificate Error: Navigation]]></Disp>
</NodeArgs>
</Step>
<Step rID="T38">
<Obj ><![CDATA[AD Setup]]></Obj>
<Details ><![CDATA[The communication and binding settings for corporate authentication have been setup on ECC]]></Details>
<Time><![CDATA[13-07-2017 - 15:48:24]]></Time>
<TimeTick>1499941104</TimeTick>
<NodeArgs eType="User" icon="11" nRep="99" Source="Action1" SourceLine="45" >
<Disp><![CDATA[AD Setup]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-07-2017 - 15:48:13" eTime="13-07-2017 - 15:48:24" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="13-07-2017 - 15:48:12" eTime="13-07-2017 - 15:48:24" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test AD_Setup_Main_RF Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>