<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="ULTP_722"><DocLocation><![CDATA[E:\Sprint\Scripts\Costco\Single Drug Batch Processing\Sprint 1\Preconditions]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Preconditions]]></DName>
<Res><![CDATA[Res1]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Step rID="T3">
<Obj ><![CDATA[Unit Cost]]></Obj>
<Details ><![CDATA[Unit Cost pricing setting has been set to User required value]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:10]]></Time>
<TimeTick>1501056670</TimeTick>
<NodeArgs eType="User" icon="3" nRep="6" >
<Disp><![CDATA[Unit Cost]]></Disp>
</NodeArgs>
</Step>
<DIter rID="T4" iterID="1" >
<Action rID="T5">
<AName><![CDATA[Action1]]></AName>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;IncentiveFee&gt; column does not exist.<BR/>Line (25): &quot;incentivefee = DataTable.Value(&quot;IncentiveFee&quot;,&quot;Global&quot;)&quot;. ]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:10]]></Time>
<TimeTick>1501056670</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="9" status="Failed" Source="Action1" SourceLine="24" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Prescriber_Paid_ID&gt; column does not exist.<BR/>Line (26): &quot;prescriberpaid = DataTable.Value(&quot;Prescriber_Paid_ID&quot;,&quot;Global&quot;)&quot;. ]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:11]]></Time>
<TimeTick>1501056671</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" status="Failed" Source="Action1" SourceLine="25" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;Prescriber_Reject_ID&gt; column does not exist.<BR/>Line (27): &quot;prescriberreject = DataTable.Value(&quot;Prescriber_Reject_ID&quot;,&quot;Global&quot;)&quot;. ]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:12]]></Time>
<TimeTick>1501056672</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="11" status="Failed" Source="Action1" SourceLine="26" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;ThirdParty1&gt; column does not exist.<BR/>Line (28): &quot;tp1 = DataTable.Value(&quot;ThirdParty1&quot;,&quot;Global&quot;)&quot;. ]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:12]]></Time>
<TimeTick>1501056672</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" status="Failed" Source="Action1" SourceLine="27" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;ThirdParty2&gt; column does not exist.<BR/>Line (29): &quot;tp2 = DataTable.Value(&quot;ThirdParty2&quot;,&quot;Global&quot;)&quot;. ]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:13]]></Time>
<TimeTick>1501056673</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="13" status="Failed" Source="Action1" SourceLine="28" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Run Error]]></Obj>
<Details plainTxt="False" ><![CDATA[The retrieve DataTable.Value operation failed. The &lt;ThirdParty3&gt; column does not exist.<BR/>Line (30): &quot;tp3 = DataTable.Value(&quot;ThirdParty3&quot;,&quot;Global&quot;)&quot;. ]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:14]]></Time>
<TimeTick>1501056674</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="14" status="Failed" Source="Action1" SourceLine="29" >
<Disp><![CDATA[Run Error]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Enterprise Pharmacy System]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:15]]></Time>
<TimeTick>1501056675</TimeTick>
<Step rID="T13">
<Obj plainTxt="False" ><![CDATA[Administration]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:15]]></Time>
<TimeTick>1501056675</TimeTick>
<Step rID="T14">
<Obj plainTxt="False" ><![CDATA[Application Settings]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaMenu]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:15]]></Time>
<TimeTick>1501056675</TimeTick>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[Application Settings.Select]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:15]]></Time>
<TimeTick>1501056675</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="19" >
<Disp><![CDATA[Application Settings.Select]]></Disp>
</NodeArgs>
</Step>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[26-07-2017 - 13:41:18]]></Time>
<TimeTick>1501056678</TimeTick>
<NodeArgs eType="General" icon="9" nRep="20" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="18" >
<Disp><![CDATA[Application Settings]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="8" nRep="17" >
<Disp><![CDATA[Administration]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="16" >
<Disp><![CDATA[Enterprise Pharmacy System]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="26-07-2017 - 13:41:10" eTime="26-07-2017 - 13:41:18" passed="0" failed="6" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="5" nRep="8" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="4" nRep="7" status="Failed" >
<Disp><![CDATA[Preconditions Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="26-07-2017 - 13:41:09" eTime="26-07-2017 - 13:41:18" passed="0" failed="6" warnings="0" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Preconditions Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>