<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HP Unified Functional Testing" productVer="12.53" os="Windows 7" host="ULTP_722"><DocLocation><![CDATA[E:\Sprint\Scripts\Costco\Login Security and Supplemental Roles\C150002\Preconditions_C150002_EPS]]></DocLocation></General>
<Doc rID="T1"   productName= "HP Unified Functional Testing"  >
<DName><![CDATA[Preconditions_C150002_EPS]]></DName>
<Res><![CDATA[Res2]]></Res>
<RunType fmStep="True" /><DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<Action rID="T3">
<AName><![CDATA[Action1]]></AName>
<Step rID="T4">
<Obj plainTxt="False" ><![CDATA[Enterprise Pharmacy System]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaWindow]]></Details>
<Time><![CDATA[25-06-2017 - 13:08:08]]></Time>
<TimeTick>1498376288</TimeTick>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[User Supplemental Role]]></Obj>
<Details plainTxt="False" ><![CDATA[JavaDialog]]></Details>
<Time><![CDATA[25-06-2017 - 13:08:08]]></Time>
<TimeTick>1498376288</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Effective Date.Type]]></Obj>
<Details plainTxt="False" ><![CDATA["micTab"]]></Details>
<Time><![CDATA[25-06-2017 - 13:08:08]]></Time>
<TimeTick>1498376288</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="10" Source="Action1" SourceLine="60" >
<Disp><![CDATA[Effective Date.Type]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Expiration Date.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["07-01-2017"]]></Details>
<Time><![CDATA[25-06-2017 - 13:08:16]]></Time>
<TimeTick>1498376296</TimeTick>
<NodeArgs eType="Replay" icon="6" nRep="12" Source="Action1" SourceLine="68" >
<Disp><![CDATA[Expiration Date.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Save.Click]]></Obj>
<Details plainTxt="False" ><![CDATA["LEFT"]]></Details>
<Time><![CDATA[25-06-2017 - 13:08:18]]></Time>
<TimeTick>1498376298</TimeTick>
<NodeArgs eType="Replay" icon="7" nRep="14" status="Warning" Source="Action1" SourceLine="69" >
<Disp><![CDATA[Save.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[Save]]></Obj>
<Details plainTxt="False" ><![CDATA[Object&nbsp;is&nbsp;disabled]]></Details>
<Time><![CDATA[25-06-2017 - 13:08:18]]></Time>
<TimeTick>1498376298</TimeTick>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[Save]]></Obj>
<Details plainTxt="False" ><![CDATA[Object's physical description:<br>to_class = JavaButton<br>Label = Save<br>]]></Details>
<Time><![CDATA[25-06-2017 - 13:08:18]]></Time>
<TimeTick>1498376298</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="17" status="Warning" nType="Description" Source="Action1" SourceLine="69" >
<Disp><![CDATA[Save]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="7" nRep="16" status="Failed" nType="Run Error" Source="Action1" SourceLine="69" >
<Disp><![CDATA[Save]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[Stop Run]]></Obj>
<Details plainTxt="False" ><![CDATA[Run stopped by user.]]></Details>
<Time><![CDATA[25-06-2017 - 13:08:18]]></Time>
<TimeTick>1498376298</TimeTick>
<NodeArgs eType="General" icon="9" nRep="18" status="Information" >
<Disp><![CDATA[Stop Run]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="5" nRep="9" status="Failed" Source="Action1" SourceLine="60" >
<Disp><![CDATA[User Supplemental Role]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="4" nRep="8" status="Failed" Source="Action1" SourceLine="60" >
<Disp><![CDATA[Enterprise Pharmacy System]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="25-06-2017 - 13:08:07" eTime="25-06-2017 - 13:08:18" passed="0" failed="1" warnings="2" ></Summary>
<NodeArgs eType="StartAction" icon="3" nRep="6" status="Failed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<Summary sTime="25-06-2017 - 13:08:07" eTime="25-06-2017 - 13:08:18" passed="0" failed="1" warnings="2" stopped="True" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Failed" >
<Disp><![CDATA[Test Preconditions_C150002_EPS Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>